name: Release Action

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: 'v3.0.6'
      source_docker_version:
        description: 'Source Docker version'
        required: true
        default: '3.0.6.XXXX'
      branch:
        description: 'Release branch'
        required: true
        default: 'release/v3.0.6'
      target_branch:
        description: 'Target branch'
        required: true
        default: 'master'

jobs:
  release:
    name: Release for ${{ matrix.repo }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo: [ "DocSpace", "DocSpace-buildtools", "DocSpace-client", "DocSpace-server" ]
    steps:
      - name: Checkout ${{ matrix.repo }}
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/${{ matrix.repo }}
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Check branch existence in ${{ matrix.repo }}
        run: |
          git ls-remote --exit-code origin "${{ github.event.inputs.branch }}" || { echo "Branch '${{ github.event.inputs.branch }}' does not exist in repository ${{ matrix.repo }}"; exit 1; }

      - name: Create Pull Request in ${{ matrix.repo }}
        id: create_pr
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh pr create -t "Merge ${{ github.event.inputs.branch }} into ${{ github.event.inputs.target_branch }}" -b '' -B ${{ github.event.inputs.target_branch }} -H "${{ github.event.inputs.branch }}" || true

      - name: Auto merge PR in ${{ matrix.repo }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          timeout 60 bash -c 'until PR_NUMBER=$(gh pr list --repo ${{ github.repository_owner }}/${{ matrix.repo }} --base ${{ github.event.inputs.target_branch }} --head "${{ github.event.inputs.branch }}" --state open --json number --jq '"'"'.[0].number'"'"'); do [ -n "$PR_NUMBER" ] && break; sleep 10; done;'
          MERGEABLE_STATUS=$(gh pr view ${PR_NUMBER} --repo ${{ github.repository_owner }}/${{ matrix.repo }} --json mergeable --jq '.mergeable')
          if [ "${MERGEABLE_STATUS}" = "MERGEABLE" ]; then
            gh pr merge ${PR_NUMBER} --merge --delete-branch
          else
            echo "PR contains conflicts or status is undefined. The merge has not been completed. Resolve conflicts manually."
          fi

      - name: Wait for all PR merges across repositories
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOS: "DocSpace DocSpace-client DocSpace-server DocSpace-buildtools"
        run: |
          echo "Waiting for the PR merge in all repositories...."
          while :; do
            MERGED=0
            for REPO in ${REPOS}; do
              PR_INFO=$(gh pr list --repo ${{ github.repository_owner }}/${REPO} --base ${{ github.event.inputs.target_branch }} --head ${{ github.event.inputs.branch }} --state all --json state,url --jq '.[0] // {state: "NOT_FOUND", url: ""}')
              PR_STATE=$(echo "${PR_INFO}" | jq -r '.state') && PR_URL=$(echo "${PR_INFO}" | jq -r '.url')
              [ "${STATE}" = "MERGED" ] && ((MERGED++))
              echo "PR state for $REPO: ${PR_STATE} ($PR_URL)"
            done
            [ "${MERGED}" -eq "$(echo ${REPOS} | wc -w)" ] && break
            sleep 30
          done

      - name: Update submodules
        if: ${{ matrix.repo == 'DocSpace' }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git submodule update --remote --merge
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -am "Update submodules"
            git push origin HEAD
          else
            echo "No changes in the submodules were detected."
          fi

      - name: Create Tag
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          TAG_NAME=${{ github.event.inputs.version }}$([ "${{ matrix.repo }}" != "DocSpace" ] && echo "-server")
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${TAG_NAME}
          git push origin ${TAG_NAME}
        
      - name: Create Release
        if: ${{ matrix.repo == 'DocSpace' }}
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          tag_name: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.version }}
          body: See changes at [CHANGELOG.md](${{ github.server_url }}/${{ github.repository }}/blob/master/CHANGELOG.md)
          draft: false
          prerelease: false

  trigger_docker_release:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Trigger workflow to release Docker
        run: |
          VERSION="${{ github.event.inputs.version }}"; VERSION="${VERSION#v}.1"
          curl -X POST \
              -u "${{ secrets.USERNAME }}:${{ secrets.DOCKER_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository_owner }}/DocSpace-buildtools/actions/workflows/106393860/dispatches" \
              -H "Accept: application/vnd.github.everest-preview+json" \
              --data "{\"ref\": \"${{ github.ref_name }}\", \"inputs\": {\"release_version\": \"${VERSION}\", \"source_version\": \"${{ github.event.inputs.source_docker_version }}\"}}"
