name: Release Action

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: 'v3.2.0'
      source_docker_version:
        description: 'Source Docker version'
        required: true
        default: '3.2.0.XXXX'
      branch:
        description: 'Release branch'
        required: true
        default: 'release/v3.2.0'
      target_branch:
        description: 'Target branch'
        required: true
        default: 'master'

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  trigger_docker_release:
    name: Trigger Docker release
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Docker release
        run: |
          DOCKER_VERSION="${{ github.event.inputs.version }}"
          DOCKER_VERSION="${DOCKER_VERSION#v}.1"
          WORKFLOWS_JSON=$(curl -s "https://api.github.com/repos/${{ github.repository_owner }}/DocSpace-buildtools/actions/workflows")
          WORKFLOW_ID=$(echo "${WORKFLOWS_JSON}" | jq -r '.workflows[] | select(.path == ".github/workflows/release-docspace.yaml") | .id')

          curl -X POST "https://api.github.com/repos/${{ github.repository_owner }}/DocSpace-buildtools/actions/workflows/${WORKFLOW_ID}/dispatches" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            --data "{\"ref\": \"${{ github.ref_name }}\", \"inputs\": {\"release_version\": \"${DOCKER_VERSION}\", \"source_version\": \"${{ github.event.inputs.source_docker_version }}\"}}"

  create_and_merge_pr:
    name: Create/merge PRs ${{ matrix.repo }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [ "DocSpace", "DocSpace-buildtools", "DocSpace-client", "DocSpace-server" ]
    steps:
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check branch existence
        run: |
          if ! gh api repos/${{ github.repository_owner }}/${{ matrix.repo }}/git/ref/heads/${{ github.event.inputs.branch }} --silent; then
            echo "::error::Branch '${{ github.event.inputs.branch }}' does not exist in repository ${{ matrix.repo }}" && exit 1
          fi

      - name: Check commits difference
        run: |
          AHEAD_BY=$(gh api repos/${{ github.repository_owner }}/${{ matrix.repo }}/compare/${{ github.event.inputs.target_branch }}...${{ github.event.inputs.branch }} --jq '.ahead_by')
          if [ "$AHEAD_BY" -eq 0 ]; then
            echo "::warning::No commits to merge in ${{ matrix.repo }}, skipping PR creation"
            echo "SKIP_PR=true" >> $GITHUB_ENV
          fi

      - name: Create Pull Request
        if: ${{ env.SKIP_PR != 'true' }}
        run: |
          PR_NUMBER=$(gh pr list --repo ${{ github.repository_owner }}/${{ matrix.repo }} \
            --base ${{ github.event.inputs.target_branch }} \
            --head ${{ github.event.inputs.branch }} \
            --state open \
            --json number --jq '.[0].number')

          if [[ -n "$PR_NUMBER" ]]; then
            echo "Pull request #$PR_NUMBER already exists in ${{ matrix.repo }}"
          else
            gh pr create --repo ${{ github.repository_owner }}/${{ matrix.repo }} \
              -t "Merge ${{ github.event.inputs.branch }} into ${{ github.event.inputs.target_branch }}" \
              -b "" \
              -B ${{ github.event.inputs.target_branch }} \
              -H ${{ github.event.inputs.branch }}
          fi

      - name: Auto merge Pull Request
        if: ${{ env.SKIP_PR != 'true' }}
        run: |
          PR_NUMBER=$(timeout 60 bash -c 'while :; do 
            NUM=$(gh pr list --repo ${{ github.repository_owner }}/${{ matrix.repo }} \
              --base ${{ github.event.inputs.target_branch }} \
              --head "${{ github.event.inputs.branch }}" \
              --state open \
              --json number --jq ".[0].number");
            [[ -n "$NUM" && "$NUM" != "UNKNOWN" ]] && echo $NUM; sleep 2; exit 0; 
          done;')

          if [ -z "${PR_NUMBER}" ]; then
            echo "::error::Failed to find open PR in ${{ matrix.repo }}" && exit 1
          fi

          MERGEABLE_STATUS=$(gh pr view "${PR_NUMBER}" \
            --repo ${{ github.repository_owner }}/${{ matrix.repo }} \
            --json mergeable --jq '.mergeable')

          if [ "${MERGEABLE_STATUS}" = "MERGEABLE" ]; then
            gh pr merge "${PR_NUMBER}" --repo ${{ github.repository_owner }}/${{ matrix.repo }} --merge
          else
            echo "::warning::PR #$PR_NUMBER in ${{ matrix.repo }} is not mergeable or contains conflicts."
          fi

  release:
    name: Release ${{ matrix.repo }}
    runs-on: ubuntu-latest
    needs: create_and_merge_pr
    strategy:
      fail-fast: false
      matrix:
        repo: [ "DocSpace", "DocSpace-buildtools", "DocSpace-client", "DocSpace-server" ]
    steps:
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Wait for all PR merges across repositories
        env:
          REPOS: "DocSpace DocSpace-client DocSpace-server DocSpace-buildtools"
        run: |
          echo "Waiting for PR merges in all repositories..."
          while :; do
            MERGED=0
            for REPO in ${REPOS}; do
              PR_INFO=$(gh pr list --repo ${{ github.repository_owner }}/${REPO} \
                --base ${{ github.event.inputs.target_branch }} --head ${{ github.event.inputs.branch }} \
                --state all --json state,url --jq '.[0] // {state: "NOT_FOUND", url: ""}')
              PR_STATE=$(echo "${PR_INFO}" | jq -r '.state') 
              PR_URL=$(echo "${PR_INFO}" | jq -r '.url')

              echo "PR state for $REPO: ${PR_STATE} ($PR_URL)"

              [ "${PR_STATE}" = "MERGED" ] && MERGED=$((MERGED + 1))
              [ "${PR_STATE}" = "NOT_FOUND" ] && REPOS=$(xargs -n1 <<< "$REPOS" | grep -vx "$REPO" | xargs)
            done
            printf '%.0s-' {1..48}; echo
            [ "${MERGED}" -eq "$(echo ${REPOS} | wc -w)" ] && break
            sleep 5
          done

      - name: Checkout repository ${{ matrix.repo }}
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/${{ matrix.repo }}
          token: ${{ secrets.GH_TOKEN }}
          submodules: recursive
          fetch-depth: 0

      - name: Update submodules (DocSpace only)
        if: ${{ matrix.repo == 'DocSpace' }}
        run: |
          git pull && git submodule update --remote --merge
          if [ -n "$(git status --porcelain)" ]; then
            git commit -am "Update submodules"
            git push origin HEAD
          else
            echo "::warning::No submodule changes detected."
          fi

      - name: Create Tag
        run: |
          TAG_NAME=${{ github.event.inputs.version }}$([ "${{ matrix.repo }}" != "DocSpace" ] && echo '-server' || echo '')
          git fetch --tags
          if git rev-parse "${TAG_NAME}" >/dev/null 2>&1; then
            echo "::warning::Tag ${TAG_NAME} already exists. Skipping tag creation."
          else
            git tag ${TAG_NAME}
            git push origin ${TAG_NAME}
          fi
        
      - name: Create Release (DocSpace only)
        if: ${{ matrix.repo == 'DocSpace' }}
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          tag_name: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.version }}
          body: See changes at [CHANGELOG.md](${{ github.server_url }}/${{ github.repository }}/blob/master/CHANGELOG.md)
          draft: false
          prerelease: false
